CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255),
    email VARCHAR(255),
    phone_number VARCHAR(100),
    address VARCHAR(500),
    linked_in_url VARCHAR(255),
    github_url VARCHAR(255),
    professional_summary CLOB,
    resume_template VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS education (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    degree VARCHAR(255),
    college_name VARCHAR(255),
    graduation_year VARCHAR(50),
    cgpa_or_percentage VARCHAR(50),
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_education_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_name VARCHAR(255),
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_skill_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_title VARCHAR(255),
    description CLOB,
    technologies_used VARCHAR(255),
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_project_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS experience (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(255),
    role VARCHAR(255),
    duration VARCHAR(255),
    description CLOB,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_experience_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS certifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    certification_name VARCHAR(255),
    organization VARCHAR(255),
    certification_year VARCHAR(50),
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_certification_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
